name = "SnapTests"
uuid = "cedb2ae3-6529-478c-a04f-d9256ac5d41f"
authors = ["Jan Weidner <jw3126@gmail.com> and contributors"]
version = "0.1.1"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DeepDiffs = "ab62b9b5-e342-54a8-a765-a90f495de1a6"

[compat]
julia = "1.8"
ArgCheck = "2"
DeepDiffs = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

